export const PATH_NAMES = {
    HOME: "",
    HASHING: "hashing",
    ENCODING_DECODING: "encoding-decoding",
    FAVOURITES: "favourites",
    HISTORY: "history",
    SETTINGS: "settings",
    COLORS: "colors",
    UUID : "uuid",
    LOREM : "lorem-ipsum",
    RANDOM_NUMBER : "random-number",
    BASE_CONVERTER : "base-converter",
    UNIT_CONVERTER : "unit-converter",
    EXPRESSION_EVALUATOR : "expression-evaluator",
    GRAPH_PLOTTER : "graph-plotter",
    PASSWORD : "password",
    URL_ENCODE_DECODE : "url-encode-decode",
    URL_PARSER : "url-parser",
    JSON_EXPLORER : "json-explorer",
    TIME_CONVERTER : "time-converter",
    README_PREVIEW : "readme-preview",
    HTML_PREVIEW : "html-preview",
    ENCODERS : "encoders",
    CIPHERS : "ciphers",
    PBKDF2 : "pbkdf2",
    HMAC : "hmac",
    HASHERS : "hashers",
}


